name: Run Tests

on: [push]

jobs:
  checker:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: install dependencies
        run: |
          pip install -r requirements-dev.txt
      - name: pre-commit, mypy & pylint
        run: |
          pre-commit run --all-files
          mypy ./stl_storage --non-interactive
          # pylint ./stl_storage
